Created User Rest
q-unite/qunite-api pull request #57
Opened 2023-06-12 11:15 UTC by NikPaukov

Updated User Service
Updated User Controller
Created Tests for User Service&Controllers

2023-06-13 16:55 UTC, xd6d commented on src/main/java/com/qunite/api/service/UserService.java
> +  Optional<List<Queue>> getCreatedQueues(Long userid);
userId

2023-06-13 17:24 UTC, Kivanval requested changes

2023-06-13 17:24 UTC, Kivanval commented on src/main/java/com/qunite/api/web/controller/UserController.java
> +
Refactor

2023-06-14 10:52 UTC, xd6d commented on src/test/java/com/qunite/api/web/UserControllerTest.java
> +        .andExpect(jsonPath("id").value(user.getId().intValue()));
check main branch and fix .intValue()

2023-06-14 10:59 UTC, Kivanval approved these changes

2023-06-14 11:10 UTC, xd6d approved these changes

2023-06-14 11:11 UTC, merged