Security jwt filter implementation
q-unite/qunite-api pull request #67
Opened 2023-06-23 15:17 UTC by vetterocki

Implemented JWT Bearer token filtration + updated existing endpoints to not violate created security rules.
Things to be updated later in this PR:
 --> Update web controllers tests with usage of security
 --> Analyze user (and according to result of discussion remodel endpoints security access) permissions to endpoints

2023-06-23 16:40 UTC, Kivanval requested changes

2023-06-23 16:40 UTC, Kivanval commented on pom.xml
> +
Put versions in the properties

2023-06-23 16:40 UTC, Kivanval commented on src/main/java/com/qunite/api/domain/User.java
> +  }
Explicit labeling is not necessary

2023-06-23 16:40 UTC, Kivanval commented on src/main/java/com/qunite/api/domain/User.java
> +
I don't really understand the point of roles

2023-06-23 16:40 UTC, Kivanval commented on src/main/java/com/qunite/api/security/JwtConstants.java
> +  public static final String ROLES = "users";
Why is it plural

2023-06-23 16:40 UTC, Kivanval commented on src/main/java/com/qunite/api/security/JwtConstants.java
> +  public static final String TOKEN_PREFIX = "Bearer ";
This is a prefix only for the token bearer, I don't see the point of putting it in a constant

2023-06-23 16:40 UTC, Kivanval commented on src/main/java/com/qunite/api/service/QueueService.java
> +  Optional<Queue> findByUserComparingToCreatorId(Long queueId, String loginData);
Strange names

2023-06-23 16:40 UTC, Kivanval commented on src/main/java/com/qunite/api/service/QueueServiceImpl.java
> +    return this.findById(queueId)
Why use this?

2023-06-23 16:40 UTC, Kivanval commented on src/main/java/com/qunite/api/service/UserServiceImpl.java
> +  }
change to createOne()

2023-06-23 16:40 UTC, Kivanval commented on src/main/java/com/qunite/api/service/UserServiceImpl.java
> +
It looks quite strange, a map to boolean

2023-06-23 16:40 UTC, Kivanval commented on src/main/java/com/qunite/api/web/controller/AuthenticationController.java
> +  @PostMapping("/register")
I propose a sign-up name for the endpoint for consistency

2023-06-23 16:40 UTC, Kivanval commented on src/main/java/com/qunite/api/service/UserServiceImpl.java
> +  private final PasswordEncoder passwordEncoder;
Code at the filter level

2023-06-23 16:59 UTC, Kivanval requested changes

2023-06-23 16:59 UTC, Kivanval commented on src/main/java/com/qunite/api/security/JwtAuthorizationFilter.java
> +    return Objects.nonNull(authHeader) && authHeader.startsWith(TOKEN_PREFIX);
I'm not sure, but nonNull can throw an error if it's null, I recommend using the usual !=null

2023-06-23 17:00 UTC, eternityduck commented on src/main/java/com/qunite/api/web/controller/UserController.java
> +    log.info("hi there");
Is this necessary?

2023-06-26 22:54 UTC, Kivanval requested changes

2023-06-26 22:54 UTC, Kivanval commented on src/main/java/com/qunite/api/service/QueueServiceImpl.java
> +        throw new AccessDeniedException("Credentials does not match the queue creator");
rename to "The user is not the creator"

2023-06-26 22:54 UTC, Kivanval commented on src/main/java/com/qunite/api/security/JwtService.java
> +  @Value("${jwt.issuer}")
use spring.application.name

2023-06-26 22:54 UTC, Kivanval commented on src/main/java/com/qunite/api/data/UserRepository.java
> +
unnecessary indents

2023-06-26 22:54 UTC, Kivanval commented on src/main/java/com/qunite/api/web/controller/UserController.java
> +  @PatchMapping("/")
/self

2023-06-26 22:54 UTC, Kivanval commented on src/main/java/com/qunite/api/web/mapper/AuthResponseMapper.java
> +  @Mapping(source = "token", target = "accessToken")
just use token field name

2023-06-26 22:54 UTC, Kivanval commented on src/main/java/com/qunite/api/web/controller/UserController.java
> +  @DeleteMapping("/")
/self

2023-06-27 17:51 UTC, Kivanval approved these changes

2023-06-29 12:52 UTC, xd6d commented on src/main/java/com/qunite/api/web/controller/UserController.java
> +  public ResponseEntity<UserDto> getSelf(Principal principal) {
missing swagger description

2023-06-30 15:51 UTC, xd6d approved these changes

2023-07-03 06:17 UTC, merged