Tests refactoring
q-unite/qunite-api pull request #74
Opened 2023-06-27 15:23 UTC by NikPaukov

2023-06-28 16:47 UTC, Kivanval approved these changes

2023-06-28 20:27 UTC, xd6d commented on src/test/java/com/qunite/api/web/QueueControllerIntegrationTest.java
> +import org.springframework.http.HttpStatus;
optimize imports

2023-06-28 20:55 UTC, xd6d commented on src/test/java/com/qunite/api/web/QueueControllerTest.java
> +        .andExpect(jsonPath("$.id", is(queue.getId().intValue())));
why did you replace 
.andExpect(content().json("{id: 1}"));
with .intValue()?

2023-06-28 20:57 UTC, xd6d commented on src/test/java/com/qunite/api/web/QueueControllerTest.java
> +        .andExpect(jsonPath("$.id", is(queue.getId().intValue())));
or maybe rewrite .intValue with .andExpect(jsonPath("$.id", is(1))); ?

2023-06-28 20:59 UTC, xd6d commented on src/test/java/com/qunite/api/web/QueueControllerTest.java
> +        .andExpect(jsonPath("$.id", is(queue.getId().intValue())));
same is above

2023-06-28 21:30 UTC, xd6d commented on src/test/java/com/qunite/api/web/QueueControllerIntegrationTest.java
> +  }
Does not look like the right way to test deletion

2023-06-28 21:37 UTC, xd6d requested changes
fix all .intValue() and code smells

2023-07-04 14:13 UTC, NikPaukov commented on src/test/java/com/qunite/api/web/QueueControllerTest.java
> +        .andExpect(jsonPath("$.id", is(queue.getId().intValue())));
same as above

2023-07-05 11:45 UTC, xd6d approved these changes

2023-07-05 11:48 UTC, merged